### PR TITLE
Update dependencies

### LINKED ISSUE #119: Update dependencies
Suggested steps:

1. Delete `package-lock.json` and `package.json`
2. Install the latest versions of the necessary dependencies
   - This will remove the unused dependencies
   - **This will generate some failures in the code that need to be fixed **(open more issues if needed)
3. Finally, generate the new version of `package-lock.json` and `package.json`.
    - It is important to remove the `^` symbol, this will fix a specific version for the packages

### PR DESCRIPTION
**Pull request by DrankoLQ**
fixes #119, #134 

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Documentation

## Description
This PR updates npm dependencies and breaking changes in the code due to these updates to support Node.js greater than 10: 12, 14, and 15. Node 10 will enter End Of Life on 2021-04-30

### CODE REVIEW

**Comment by anthares101** [comment]
@VictorNS69 i tried this changes with the examples repository. The 1.createEntityAlastriaID example fails with this error:
```
(node:43162) UnhandledPromiseRejectionWarning: Error: invalid BigNumber string (argument="value", value="a9728125c573924b2b1ad6a8a8cd9bf6858ced49", code=INVALID_ARGUMENT, version=bignumber/5.1.0)
    at Logger.makeError (/home/anthares101/Proyectos/alastria-identity-example/node_modules/@ethersproject/logger/lib/index.js:180:21)
    at Logger.throwError (/home/anthares101/Proyectos/alastria-identity-example/node_modules/@ethersproject/logger/lib/index.js:189:20)
    at Logger.throwArgumentError (/home/anthares101/Proyectos/alastria-identity-example/node_modules/@ethersproject/logger/lib/index.js:192:21)
    at Function.BigNumber.from (/home/anthares101/Proyectos/alastria-identity-example/node_modules/@ethersproject/bignumber/lib/bignumber.js:201:27)
    at Writer._getValue (/home/anthares101/Proyectos/alastria-identity-example/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:82:60)
    at Writer.writeValue (/home/anthares101/Proyectos/alastria-identity-example/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:96:37)
    at AddressCoder.encode (/home/anthares101/Proyectos/alastria-identity-example/node_modules/@ethersproject/abi/lib/coders/address.js:31:23)
    at /home/anthares101/Proyectos/alastria-identity-example/node_modules/@ethersproject/abi/lib/coders/array.js:71:19
    at Array.forEach (<anonymous>)
    at Object.pack (/home/anthares101/Proyectos/alastria-identity-example/node_modules/@ethersproject/abi/lib/coders/array.js:57:12)
    at TupleCoder.encode (/home/anthares101/Proyectos/alastria-identity-example/node_modules/@ethersproject/abi/lib/coders/tuple.js:36:24)
    at AbiCoder.encode (/home/anthares101/Proyectos/alastria-identity-example/node_modules/@ethersproject/abi/lib/abi-coder.js:86:15)
    at ABICoder.encodeParameters (/home/anthares101/Proyectos/alastria-identity-example/node_modules/web3-eth-abi/lib/index.js:121:27)
    at ABICoder.encodeFunctionCall (/home/anthares101/Proyectos/alastria-identity-example/node_modules/web3-eth-abi/lib/index.js:263:63)
    at Object.prepareAlastriaID (/home/anthares101/Proyectos/alastria-identity-example/node_modules/alastria-identity-lib/dist/txFactory/identityManagerTransactionFactory.js:28:40)
    at preparedAlastriaId (/home/anthares101/Proyectos/alastria-identity-example/exampleFirstEntity/1.createEntityAlastriaID.js:72:57)
(node:43162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
If i add `0x` to the entity1 address that error gets fixed but the transaction fails:
```
Error: Returned error: known transaction: 349192bdb60ffb78becfe84745d2abe49e7431ca756717b7b89753f51603c249
    at Object.ErrorResponse (/home/anthares101/Proyectos/alastria-identity-example/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/anthares101/Proyectos/alastria-identity-example/node_modules/web3-core-requestmanager/lib/index.js:303:36
    at XMLHttpRequest.request.onreadystatechange (/home/anthares101/Proyectos/alastria-identity-example/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/anthares101/Proyectos/alastria-identity-example/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/anthares101/Proyectos/alastria-identity-example/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/anthares101/Proyectos/alastria-identity-example/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/anthares101/Proyectos/alastria-identity-example/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  data: null
}
```

**Comment by VictorNS69** [comment]
> If i add 0x to the entity1 address that error gets fixed but the transaction fails:

Hmmm... we should investigate this error further (with more log traces).

Is it possible that the `nonce` is not being set correctly?

**Comment by anthares101** [comment]
@VictorNS69 i used the examples in the master branch because the alastria-identity repo is still using the old addreses

**Comment by anthares101** [comment]
I just noticed that i was able to create the transaction 0x to the entity1 address but it hangs and never returns. After that if i try again the example the error i commented above happens @VictorNS69

**Comment by anthares101** [comment]
> The [Smart Contract](https://github.com/alastria/alastria-identity/blob/master/contracts/identityManager/AlastriaIdentityEntity.sol#L48) checks that the address you are trying to set as Entity is not an active Entity at the moment [(`notIdentityEntity(_addressEntity)`)](https://github.com/alastria/alastria-identity/blob/master/contracts/identityManager/AlastriaIdentityEntity.sol#L26).
> 
> Maybe the problem is that you need to create a new DID for the identity you are trying to set as Entity?
> 
> Also, if you can print the raw transaction and post it here, maybe we can see something wrong with it.

Ok so the result for the `1.createEntity2AlastriaID.js` is the same, it just hangs like i show you bellow:

```
node 1.createEntity2AlastriaID.js                                                                                                                                                            ─╯
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.

 ------ Example of creating an Alastria ID for a Entity2 with Entity1. ------ 


 ------ A promise all where prepareAlastriaID and createAlsatriaID transactions are signed and sent ------ 

        signedAT: 
 eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksiLCJraWQiOiJkaWQ6YWxhOnF1b3I6cmVkdDoxMmVlYUNDQTllRWJCNzhlQjk3ZDdjYWM2YiNrZXlzLTEiLCJqd2siOiIweDM1NmUzZmNlNDM1ZDg3MjkwNjJlNTJkMjYzYzBjNzA1YjNjNWUyMDFhOWE5NjA4Y2RiMDcwNzY0ZTZiOGRmMzBhZTg0MjNiNDM5YTdhZjJiY2MzNTI5Nzc4MzQxYWIwNmMxZTQ0NDExMzUyZjIxN2I2OGNlNDRhNjczYTFkZjYzIn0.eyJpc3MiOiJkaWQ6YWxhOnF1b3I6cmVkVDpkMmY4NjhmMDU2ZWYzYTQ4YmJjOGQ0NDZkZmVkNDExZTliZjkzYWIwIiwiZ3d1IjoiaHR0cHM6Ly9yZWd1bGFyLnRlbHNpdXMuYmxvY2tjaGFpbmJ5ZXZlcmlzLmlvOjIwMDAiLCJjYnUiOiJodHRwczovL3NlcnZpY2Vwcm92aWRlci5hbGFzdHJpYS5ibG9ja2NoYWluYnlldmVyaXMuaW8vYXBpL2xvZ2luLyIsImlhdCI6MTYxOTA3ODc2NywiYW5pIjoicmVkVCIsIm5iZiI6MTU2Mzc4Mjc5MiwiZXhwIjoxNTYzNzgzMzkyLCJqdGkiOiJ6ZTI5OHk0MnNiYSJ9.4bFsSGxz2eRD9xvkTGqdHGPNwIdaxLQEPYlHhoj34ihyMwlOc-kAadLkJi6Ck1RVx2hB0T4CIHCBlGCWDPP6tg
        signedAIC: 
 eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJAY29udGV4dCI6WyJodHRwczovL2FsYXN0cmlhLmdpdGh1Yi5pby9pZGVudGl0eS9hcnRpZmFjdHMvdjEiXSwidHlwZSI6WyJBbGFzdHJpYUlkZW50aXR5Q3JlYXRpb24iXSwiY3JlYXRlQWxhc3RyaWFUWCI6IjB4ZjkwMTg4ODIwM2Q4ODA4MzA5MjdjMDk0YmQ0YTJjODRlZGI5N2JlNWJlZmY3Y2QzNDFiZDYzNTY3ZTczZjhjOTgwYjkwMTI0NmQ2OWQ5OWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBjNDUwMzgyYzFhMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODA2MTMzMzM2NTM1MzY2MTM4MzA2MjM5NjQ2MzM4MzM2MTM0MzQzNTM2MzIzNjM1NjQzODM3Mzc2MzMwMzczNjM1NjM2NTYxMzczNjMxMzQzNjY1MzYzMjM1MzUzNzMyNjY2MzM2MzczOTM4MzAzNDY2MzgzODM2MzczMjMyMzI2MzYxMzM2MzM4MzEzNjM0MzMzMzYxMzk2MjM2NjUzNjM2MzkzMDYyMzA2MjM4NjUzOTMxMzk2NjY2NjEzODM3MzQzOTM4MzIzNzMwMzY2NTM4MzEzMjMzMzEzNDYxNjE2NTMwMzk2NDM4MzU2NjYzMzYzMjY2NjMzNDY2NjEzMzYzMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyNmEwNDRmYjZmZTRkZWMzYzdmMDIzNjIwMDIwZmI2MDVhZTBmZDc5MzY1MWEwMWRhOWNiNjk2ODNjYWYzNjhiMjY3ZWEwMDNhODgyYzAxZjNkMmE4MGFiNTM1ZTA0ZTUxODdkOWI2YmNjNjNiY2RiMjBjMjVmYzJhYzBiYTg1MzE5NWRkOCIsImFsYXN0cmlhVG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpGVXpJMU5rc2lmUS5JbHdpWlhsS01HVllRV2xQYVVwTFZqRlJhVXhEU21oaVIyTnBUMmxLUmxWNlNURk9hM05wVEVOS2NtRlhVV2xQYVVwcllWZFJObGxYZUdoUGJrWXhZak5KTm1OdFZtdGtSRzk0VFcxV2JGbFZUa1JSVkd4c1VsZEtRMDU2YUd4UmFtc3pXa1JrYWxsWFRUSlphVTV5V2xoc2VreFVSV2xNUTBweFpESnphVTlwU1hkbFJFMHhUbTFWZWxwdFRteE9SRTB4V2tSbk0wMXFhM2RPYWtwc1RsUkthMDFxV1hwWmVrSnFUbnBCTVZscVRtcE9WMVY1VFVSR2FFOVhSVFZPYWtFMFdUSlNhVTFFWTNkT2Vsa3dXbFJhYVU5SFVtMU5la0pvV2xSbk1FMXFUbWxPUkUwMVdWUmthRnBxU21sWk1rMTZUbFJKTlU1Nll6Uk5lbEY0V1ZkSmQwNXRUWGhhVkZFd1RrUkZlRTE2VlhsYWFrbDRUakpKTWs5SFRteE9SRkpvVG1wamVsbFVSbXRhYWxsNlNXNHdMbVY1U25Cak0wMXBUMmxLYTJGWFVUWlpWM2hvVDI1R01XSXpTVFpqYlZaclZrUndhMDF0V1RST2FtaHRUVVJWTWxwWFdYcFpWRkUwV1cxS2FrOUhVVEJPUkZwcldtMVdhMDVFUlhoYVZHeHBXbXByZWxsWFNYZEphWGRwV2pOa01VbHFiMmxoU0ZJd1kwaE5Oa3g1T1hsYVYyUXhZa2RHZVV4dVVteGlTRTV3WkZoTmRWbHRlSFpaTW5ScVlVZEdjR0p0U2pWYVdGcHNZMjFzZWt4dGJIWlBha2wzVFVSQmFVeERTbXBaYmxWcFQybEtiMlJJVW5kamVtOTJURE5PYkdOdVduQlpNbFozWTIwNU1tRlhVbXhqYVRWb1lrZEdlbVJJU25CWlV6VnBZa2M1YW1FeVRtOVpWMngxV1c1c2JHUnRWbmxoV0UxMVlWYzRkbGxZUW5CTU1uaDJXakpzZFV4NVNYTkpiV3hvWkVOSk5rMVVXWGhQVkVFelQwUmpNazU1ZDJsWlZ6VndTV3B2YVdOdFZtdFdRMGx6U1cwMWFWcHBTVFpOVkZVeVRYcGpORTFxWXpWTmFYZHBXbGhvZDBscWIzaE9WRmw2VG5wbmVrMTZhM2xNUTBweFpFZHJhVTlwU2paYVZFazFUMGhyTUUxdVRtbFpVMG81TGpSaVJuTlRSM2g2TW1WU1JEbDRkbXRVUjNGa1NFZFFUbmRKWkdGNFRGRkZVRmxzU0dodmFqTTBhV2g1VFhkc1QyTXRhMEZoWkV4clNtazJRMnN4VWxaNE1taENNRlEwUTBsSVEwSnNSME5YUkZCUU5uUm5YQ0lpLm4xbmozSm9IaVZzU1JNa3ZCaE11c25WdXhaZmFGOUM5Sm1tZzFFeEJDSXhvSl85dzc3WXZ5UHJMWlF2YVIwd05KQTJNWmh6QTY2M3hsTnMwM1FkWFBnIiwicHVibGljS2V5IjoiMHhhMzNlNTZhODBiOWRjODNhNDQ1NjI2NWQ4NzdjMDc2NWNlYTc2MTQ2ZTYyNTU3MmZjNjc5ODA0Zjg4NjcyMjJjYTNjODE2NDMzYTliNmU2NjkwYjBiOGU5MTlmZmE4NzQ5ODI3MDZlODEyMzE0YWFlMDlkODVmYzYyZmM0ZmEzYyJ9.2CUmDFjsW-3pFp-JTRZzPf2HlOfNBJ2DbJEs5Mqy-wgXLn7JG3j1iOxCY4w26u3M4y_L_2eFMXAJDMThgcIvjw
HASH:  0xd38ed79537026d54a6931f0bf0e73a1d32594780bd8ab5fbca0a8cb3ca9cf4a0
```
The transaction:

```
{
  to: '0xbd4a2c84edb97be5beff7cd341bd63567e73f8c9',
  data: '0x597b2e9b000000000000000000000000bd4a2c84edb97be5beff7cd341bd63567e73f8c900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002445748b42000000000000000000000000ad88f1a89cf02a32010b971d8c8af3a2c7b3bd9400000000000000000000000000000000000000000000000000000000',
  gasLimit: 600000,
  gasPrice: 0,
  nonce: 3808
}
```

**Comment by anthares101** [comment]
I tested this again with the new contracts using a clean branch: https://github.com/alastria/alastria-identity-lib/tree/feature/update-dependencies and looks like it enters in a loop and is all the time printing the transaction. Can you try it out @VictorNS69 ? I used the `1.createEntityAlastriaID` example.

**Comment by anthares101** [comment]
Ok, i added the `0x` to the Web3 call too and the problem is gone and looks like is working. I will try to update all the examples and test them out.

**Comment by VictorNS69** [comment]
So, as the #146 is already merged, this draft is not necessary, right @anthares101 ?

**Pull request closed without merging**
